### ISSUE TITLE
hacklab.fi dns changes to get ghpages ssl working

### ISSUE THREAD

**Issue by tswfi** [hacklab-fi/itinfra#10]
Github allows ssl on custom domains: https://github.blog/2018-05-01-github-pages-custom-domains-https/

but we need to do a small change to our dns for this to work. From this page: https://help.github.com/articles/setting-up-an-apex-domain/

either with alias
hacklab.fi.   ALIAS   hacklab-fi.github.io

or with a records:
hacklab.fi.    A     185.199.108.153
hacklab.fi.    A     185.199.109.153
hacklab.fi.    A     185.199.110.153
hacklab.fi.    A     185.199.111.153

and remove the old A records:
$ dig +noall +answer hacklab.fi
hacklab.fi.             3600    IN      A       192.30.252.153
hacklab.fi.             3600    IN      A       192.30.252.154

after this is done the domain needs to be removed and added again to the site to trigger ssl certificate generation (at least I think so :)

**Comment by tanelikaivola** [comment]
Change completed with A records.
