### ISSUE TITLE
Lappeenranta Hacklab website

### ISSUE THREAD

**Issue by niilasoika** [hacklab-fi/itinfra#21]
I would like to request a subdomain for Lappeenranta Hacklab.
Domain: lappeenranta.hacklab.fi
CNAME pointing to: lprhacklab.github.io

**Comment by tswfi** [comment]
CNAME record added.

hacklab.fi dns are hosted on google cloud dns and usually we build own project and zone for each city (thus allowing the city to self manage the zone). But as the request is for just one CNAME it is not possible to have both NS and CNAME record for lappeenranta.hacklab.fi (nor to have the CNAME inside the city zone as that is considered apex for the zone). Thus the project and zone were not created for now. Those can be added later when the requirements increase.

@niilasoika Two requests to get more visibility for Lappeenranta and Hacklab ry:
1) add link back to hacklab.fi site to lappeenranta.hacklab.fi
2) make a pull request to hacklab.fi site repository (https://github.com/hacklab-fi/hacklab-website) and add Lappeenranta onto the list of Cities (maybe under a new "aloittamassa" header?)

**Comment by niilasoika** [comment]
Thank you! Will do :)
