### ISSUE TITLE
Peertube-instanssi

### ISSUE THREAD

**Issue by vranki** [hacklab-fi/itinfra#23]
Youtuben paskoontumisen myötä olisi kysyntää hakkereille tarjottavastia Peertube-instanssista.

Käyttäjätunnukset voisivat tulla hacklab.fi SSO:lla suoraan. 

Säännöistä en ole ihan varma. Ainakin hakkeri/tekniikka/stem-aiheet olisivat sallittuja, mutta olisiko henk.koht kissavideot sun muut? Ja luonnollisesti videoiden täytyisi olla käyttäjän tekemiä tai ainakin tekijänoikeudet kunnossa. Levyquotalla voidaan pitää käyttömäärä kohtuullisena, mutta toisaalta levy on halpaa enkä usko että lähitulevaisuudessa tilankäyttö tulee ongelmaksi.

# Tarvitaan:

- [x] Virtuaalipalvelin, mielellään isolla levyllä. Vaikkapa 200-500Gb alkuun. Levyä tulisi pystyä kasvattamaan tulevaisuudessa.
- [x] Domain-nimi video.hacklab.fi osoittamaan k.o palvelimeen
- [x] Peertuben asennus (voin hoitaa)
- [ ] SSO-integraatio

**Comment by olmari** [comment]
@vranki Laitetaan Trinitylle.

domain järjestyy

Laitan X määrää erillistä pyörivää ruostetta, peertuben hillovarasto tarvitsee osoittaa sitä kohti sitten, mountpoint toki vapaasti valittavissa.

**Comment by olmari** [comment]
Instanssi olemassa, SSO-integraatiota ei, koska siinä oli jokin perustavanlaatuinen jännäke, jota en kyllä nyt just muista mikä oli...

**Comment by olmari** [comment]
IMHO Suljetaan tämä valmiina, avataan erikseen tiketti SSO-integraatiolle tarvittaessa, josko se joskus onnistuis järkevästi...
